// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameStateBase.h"
#include "Sound/SoundWave.h"
#include "LootingLootersGameStateBase.generated.h"

/**
 * 
 */
UCLASS()
class LOOTINGLOOTERS_API ALootingLootersGameStateBase : public AGameStateBase
{
	GENERATED_BODY()
		ALootingLootersGameStateBase();
	
public:

	//On begin runtime, generate the level and its elements.
	virtual void BeginPlay() override;

	virtual void Tick( float DeltaSeconds ) override;

	//Server call : Spawn a random level.
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateRandomRoomLayout();

	//Server call : Populate the level with assets and doors.
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_PopulateRoomSockets();

	//Server call : Connect the level's doors together.
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateRandomRoomConnections();

	//Server call : Spawn fresh loot in rooms.
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateLoot();

	//Copies the room list.
	void GetRoomArray(TArray<class ARoomActorBase*>& RoomArray);

	//Team 1 materials
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamOneMaterials;

	//Team 2 materials
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamTwoMaterials;

	//Team 3 materials
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamThreeMaterials;

	//Team 4 materials
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamFourMaterials;

	//Login data.
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerOneLoggedIn;

	//Login data.
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerTwoLoggedIn;

	//Login data.
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerThreeLoggedIn;

	//Login data.
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerFourLoggedIn;
	
	//Our Timer to control how long a match lasts. 
	UPROPERTY(Replicated)
		FTimerHandle MatchTimer;

	//Our Timer for setting how much buffer after a match that the screen hovers before we move back to the main lobby.
	UPROPERTY(Replicated)
		FTimerHandle EndBufferTime;

	//Default match length.
	UPROPERTY(EditAnywhere, Replicated)
		float MatchLength = 60.0f;

	//Default buffer length
	UPROPERTY(EditAnywhere, Replicated)
		float BufferLength = 10.0f;

	//Bool to flag the hud when a match ends.
	UPROPERTY(BlueprintReadOnly, Replicated)
		bool MatchEnding = false;

	//used for a HUD based Countdown timer
	UPROPERTY(Replicated, BlueprintReadOnly)
		float MatchCountDown = MatchLength;

	//Called when the MatchTimer Ends. Creates another timer that when complete Actually closes the game
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_StartEndGame();

	//Called by EndBufferTimer. This calls the GameMode to begin EndGame.
	UFUNCTION(Server, Reliable, WithValidation)
		void Server_EndGame();

protected:

	//All rooms generated by the random generation process
	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Rooms")
		TArray<class ARoomActorBase*> Rooms;

	//CURRENTLY UNUSED BUT CAN BE REIMPLEMENTED IF WE FIX THE SOUND ISSUE WITH LOADING FILES//

	//virtual void LoadSoundMap();

	//UPROPERTY(VisibleAnywhere, Category = "Sound", Replicated)
	//	TMap<FString, USoundWave*> SoundsMap;

	//public:

	//	USoundWave* GetSoundWave(FString name);

};
