// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameStateBase.h"
#include "LootingLootersGameStateBase.generated.h"

/**
 * 
 */
UCLASS()
class LOOTINGLOOTERS_API ALootingLootersGameStateBase : public AGameStateBase
{
	GENERATED_BODY()
		ALootingLootersGameStateBase();
	
public:

	virtual void BeginPlay() override;

	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateRandomRoomLayout();

	UFUNCTION(Server, Reliable, WithValidation)
		void Server_PopulateRoomSockets();

	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateRandomRoomConnections();

	UFUNCTION(Server, Reliable, WithValidation)
		void Server_GenerateLoot();

	//Copies the room list.
	void GetRoomArray(TArray<class ARoomActorBase*>& RoomArray);

	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamOneMaterials;

	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamTwoMaterials;

	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamThreeMaterials;

	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = Materials, Replicated)
		class UMaterialInterface* TeamFourMaterials;

	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerOneLoggedIn;

	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerTwoLoggedIn;

	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerThreeLoggedIn;

	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = Gameplay, Replicated)
		bool PlayerFourLoggedIn;
	
protected:

	//All rooms generated by the random generation process
	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Rooms")
		TArray<class ARoomActorBase*> Rooms;

	//how many rooms we're making
	UPROPERTY(EditAnywhere, Category = "Rooms")
		int Total_Rooms_To_Generate = 10;

};
